In [1]:
import numpy as np

In [2]:
data=np.array([[1,2,3],[4,5,6]])

In [3]:
data*10

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
data+data

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('int64')

In [7]:
data1=[1,2.5,3,0,10]
arr1=np.array(data1)
arr1 # it will change them all to float become they must be of same time and to not lose any data of our float numbers

array([ 1. ,  2.5,  3. ,  0. , 10. ])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# if you want to give your array more dimensions give it a tuple=(rows,cols)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [15]:
lst=[1,2,3,4,5]
arr1=np.array(lst)
arr2=np.asarray(lst)
adderese_of_lst=id(lst)
add_of_arr1=id(arr1)
add_of_arr2=id(arr2)
print(add_of_arr1,add_of_arr2,adderese_of_lst)

134021833371120 134021833373424 134021833110272


In [16]:
x=np.array([1,2,3])
arr2=np.asarray(x)
print(id(arr2))
arr1=np.array(x)
print(id(arr1))
print(id(x))

134021833341424
134021833342096
134021833341424


In [19]:
arr1=np.array([1,2.5,3],dtype=np.int32)
arr1

array([1, 2, 3], dtype=int32)

In [22]:
arr1=arr1.astype(np.float64)

In [23]:
arr1.dtype

dtype('float64')

In [29]:
numric_string=np.array(['1.22','1.50','1.345'])
numric_string.dtype
numric_string=numric_string.astype(np.float64)
numric_string.dtype

dtype('float64')

In [31]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice=arr[5:8]
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [37]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [38]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d[0][2]==arr2d[0,2]

True

In [39]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[100,200,800]]])

In [43]:
arr3d[0,0,1]

2